--- #YAML:1.0
name:               Dancer-Plugin-EncodeID
version:            0.01
abstract:           Encode/Decode (or obfuscate) IDs in URLs
author:
    - Assaf Gordon <gordon@cshl.edu>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::Blowfish:  0
    Dancer:           1.3
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
